name: Down Merge From main to develop
on: 
  push:
    branches: [main]

env:
  MAIN_BRANCH: main
  DEVELOP_BRANCH: develop
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  down-merge:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set Git Config
        id: "config"
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Create Pull Request
        id: "create-pr"
        run: |
          echo "$ Creating Merge PR"
          url=$(gh pr create -B ${{ env.DEVELOP_BRANCH }} -H ${{ env.MAIN_BRANCH }} --title 'Merge ${{ env.MAIN_BRANCH }} into ${{ env.DEVELOP_BRANCH }}' --body 'Created by Github action')
          echo "$ PR created: $url"

          echo "url=$url" >> $GITHUB_OUTPUT
          
      - name: Check PR Status
        id: "pr-status"
        run: |
          echo "$ PR Status"
          gh pr ready $url
          status=$(gh pr status --json mergeable)
          if echo "$status" | grep -q "CONFLICTING"; then
            echo "The are conflicts that need to be solved manually"
            echo "Finishing with error"
            exit 1
          fi

          echo "url=$url" >> $GITHUB_OUTPUT
      - name: Auto Merge PR
        id: "merge-pr"
        run: |
          echo "$ Attempting auto merge"
          echo $url
          gh pr merge $url --auto --merge
        
          echo "-----"
          echo "Done"
