name: From main to develop
on: 
  push:
    branches: [main]

env:
    MAIN_BRANCH: main
    DEVELOP_BRANCH: develop

jobs:
  merge-main-back-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git Config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"