on:
  push:
    branches:
      # - main
      - 'release/**'
      # - develop

jobs:
  downmerge:
    runs-on: ubuntu-latest
    steps:
      - id: downmerge
        name: Down-Stream Version AutoMerger
        uses: maikuru/downstream-version-automerge@v1.1.2
        with:
          production-branch: 'main'
          development-branch: 'develop'
          release-pattern: 'release/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}